name: provision infrastructure v1 on creation
on:
  workflow_dispatch:
  schedule:
   - cron: 30 * * * mon-fri
permissions:
  contents: read
  pages: write
  id-token: write
jobs:
  infra-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v2'
      with:
        project_id: 'my-second-project-453608'
        service_account: 'github-wif@my-second-project-453608.iam.gserviceaccount.com'
        #workload_identity_provider: 'projects/464582918280/locations/global/workloadIdentityPools/github/providers/my-repo'
        #workload_identity_provider: 'projects/464582918280/locations/global/workloadIdentityPools/github1/providers/my-repo1'
    
    - uses: hashicorp/setup-terraform@v3

    - name: terraform init
      run: cd terraform && ./plan.sh
    
    - name: terraform plan
      run: cd terraform && ./apply.sh


